AD/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
from wadmin.views import HomeView, uploadImage

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view(), name='home'),
                       url(r'^wadmin/', include('wadmin.urls', namespace='wadmin')),
                       url(r'^uploadImage/$', uploadImage),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

wadmin/urls.py
# coding=utf-8
# Date: 14/11/21
# Time: 09:11
# Email:fanjunwei003@163.com
from django.conf.urls import patterns, url
from views import *

__author__ = u'范俊伟'

urlpatterns = patterns('wadmin',
                       url(r'^img_code/$', get_img_code, name='img_code'),
                       url(r'^register/$', RegisterView.as_view(), name='register'),
                       url(r'^login/$', LoginView.as_view(), name='login'),
                       url(r'^logout/$', logout, name='logout'),
                       url(r'^change_password/$', ChangePasswordView.as_view(), name='change_password'),
                       url(r'^test_ad/$', TestADView.as_view(), name='test_ad'),
                       url(r'^send_article/$', SendArticleView.as_view(), name='send_article'),
                       url(r'^article/(?P<id>\d*?)$', ArticleView.as_view(), name='article'),
)

wadmin/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Article(models.Model):
    user = models.ForeignKey(User, verbose_name=u'作者')
    title = models.CharField(max_length=255, verbose_name=u'标题')
    content = models.TextField(max_length=255, null=False, blank=True, verbose_name=u'内容')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name=u'发表时间')
    visit_count = models.IntegerField(default=0, verbose_name=u'访问次数')


class UploadImage(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'名称')
    image = models.ImageField(upload_to='image/%Y/%m/%d')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')

wadmin/forms.py
# coding=utf-8
# Date: 14/11/21
# Time: 17:21
# Email:fanjunwei003@163.com
import uuid
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.forms import SplitDateTimeWidget
from wadmin.models import Article


__author__ = u'范俊伟'


class LoginForm(AuthenticationForm):
    img_code = forms.CharField(label='验证码')

    def clean_img_code(self):
        img_code = self.cleaned_data.get('img_code')
        if img_code != self.request.session['login_img_code']:
            self.request.session['login_img_code'] = None
            raise forms.ValidationError('验证码错误')
        self.request.session['login_img_code'] = None
        return img_code

    def clean(self):
        if not self.errors:
            super(LoginForm, self).clean()
        else:
            return self.cleaned_data


class RegisterForm(forms.ModelForm):
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(RegisterForm, self).__init__(*args, **kwargs)

    error_messages = {
        'duplicate_username': "用户已存在",
        'password_mismatch': "两次输入的密码不同",
    }
    username = forms.RegexField(label="用户名", max_length=30,
                                regex=r'^[\w.@+-]+$',
                                help_text="用户名只允许为字母、数字和字符 @/./+/-/_ 。",
                                error_messages={
                                    'invalid': "用户名只允许为字母、数字、下划线"})
    password1 = forms.CharField(label="密码",
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label="确认密码",
                                widget=forms.PasswordInput,
    )

    email = forms.EmailField(label='Email')

    img_code = forms.CharField(label='验证码')

    class Meta:
        model = User
        fields = ("username",)


    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )


    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if self.Meta.model.objects.filter(email=email).exists():
            raise forms.ValidationError(u'Email已存在,请输入其他地址')
        return email

    def clean_img_code(self):
        img_code = self.cleaned_data.get('img_code')
        if img_code != self.request.session['login_img_code']:
            self.request.session['login_img_code'] = None
            raise forms.ValidationError('验证码错误')
        self.request.session['login_img_code'] = None
        return img_code

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class ChangePasswordForm(forms.Form):
    error_messages = {
        'password_mismatch': "两次输入的密码不同",
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    password_old = forms.CharField(label="原始密码",
                                   widget=forms.PasswordInput)
    password_new1 = forms.CharField(label="新密码",
                                    widget=forms.PasswordInput)
    password_new2 = forms.CharField(label="确认新密码",
                                    widget=forms.PasswordInput)


    def clean_password_new2(self):
        password_new1 = self.cleaned_data.get("password_new1")
        password_new2 = self.cleaned_data.get("password_new2")
        if password_new1 and password_new2 and password_new1 != password_new2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password_new2


    def clean_password_old(self):
        password_old = self.cleaned_data.get("password_old")
        if not self.request.user.check_password(password_old):
            raise forms.ValidationError(u'原始密码错误')
        return password_old


    def save(self, commit=True):
        user = self.request.user
        user.set_password(self.cleaned_data["password_new1"])
        if commit:
            user.save()
        return user


class ArticleForm(forms.ModelForm):
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(ArticleForm, self).__init__(*args, **kwargs)


    class Meta:
        model = Article
        fields = ['title', 'content']

    def save(self, commit=True):
        object = super(ArticleForm, self).save(commit=False)
        object.user = self.request.user
        object.save()

wadmin/views.py
# coding=utf-8
import base64
from functools import update_wrapper
import json
import os
import random
from django import http
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.utils.decorators import classonlymethod
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.generic.edit import FormMixin
from django.views.generic.list import MultipleObjectMixin
from util.tools import getResult
from wadmin.forms import *
from django.utils.http import urlencode
from django.db import models
from wadmin.models import Article, UploadImage

DOT = '.'
PREVIOUS_PAGE = '<'
NEXT_PAGE = '>'


def uploadImage(request):
    image = request.FILES.get('image', None)

    if image:
        dbImage = UploadImage()
        dbImage.name = image.name
        image.file.size = image.size
        dbImage.image.save(image.name, image.file)
        dbImage.save()
        o = {
            'upload': {
                'links': {
                    'original': dbImage.image.url
                }
            },
        }
        return HttpResponse(json.dumps(o), 'application/json')
    return getResult(False)


def get_img_code(request):
    string = '12345679ACEFGHKMNPRTUVWXY'
    ImageCode_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'tools', 'ImageCode.jar').replace('\\',
                                                                                                                '/')
    code = ''.join(random.sample(string, 4))
    request.session['login_img_code'] = code.lower()
    res = os.popen('java -jar ' + ImageCode_path + ' ' + code)
    data = base64.decodestring(res.read())
    return HttpResponse(data, 'image/png')


def logout(request):
    auth_logout(request)
    return http.HttpResponseRedirect(request.REQUEST.get('next', reverse('home')))


def admin_view_decorator(func):
    def admin_view(cls, cached=False, **kwargs):
        view = func(cls, **kwargs)

        def has_permission(request):
            if request.user.is_active:
                return True
            else:
                return False

        def inner(request, *args, **kwargs):
            if not has_permission(request) and getattr(cls, 'need_site_permission', True):
                return LoginView.as_view()(request, *args, **kwargs)
            return view(request, *args, **kwargs)

        if not cached:
            inner = never_cache(inner)
        return update_wrapper(inner, view)

    return admin_view


class BaseView(TemplateView):
    need_site_permission = True
    template_name = 'wadmin/base.html'

    def get_context_data(self, **kwargs):
        kwargs = super(BaseView, self).get_context_data(**kwargs)
        kwargs['url'] = self.request.get_full_path()
        if hasattr(self, 'form'):
            kwargs['form'] = self.form
        return kwargs

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        qs = urlencode(p)
        if qs:
            return '?%s' % qs
        else:
            return ''

    @classonlymethod
    @admin_view_decorator
    def as_view(cls, **initkwargs):
        return super(BaseView, cls).as_view(**initkwargs)


class LoginView(BaseView):
    template_name = 'wadmin/login.html'


    @classonlymethod
    def as_view(cls, **initkwargs):
        return super(BaseView, cls).as_view(**initkwargs)

    def post(self, request, *args, **kwargs):
        self.form = LoginForm(request=request, data=request.POST)
        if self.form.is_valid():
            auth_login(request, self.form.get_user())
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            return http.HttpResponseRedirect(request.REQUEST.get('next', reverse('home')))
        else:
            return self.get(request, *args, **kwargs)


class RegisterView(BaseView):
    need_site_permission = False
    template_name = 'wadmin/register.html'


    @classonlymethod
    def as_view(cls, **initkwargs):
        return super(BaseView, cls).as_view(**initkwargs)

    def post(self, request, *args, **kwargs):
        self.form = RegisterForm(request=request, data=request.POST)
        if self.form.is_valid():
            self.form.save()
            return http.HttpResponseRedirect(request.REQUEST.get('next', reverse('home')))
        else:
            return self.get(request, *args, **kwargs)


class FrameView(BaseView):
    def get_site_menu(self):
        if self.request.user.is_active:
            return [
                {'title': u'功能', 'menus':
                    [
                        {'title': u'发笑话',
                         'icon': 'glyphicon-star',
                         'url': reverse('wadmin:send_article')},
                    ]
                },
            ]
        else:
            return []

    def get_context_data(self, **kwargs):
        kwargs = super(FrameView, self).get_context_data(**kwargs)
        kwargs['nav_menu'] = self.get_site_menu()
        return kwargs

    template_name = 'wadmin/frame.html'


class BaseListView(MultipleObjectMixin, FrameView):
    paginate_by = 100


    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super(BaseListView, self).get(request, *args, **kwargs)

    def get_paginator(self, queryset, per_page, orphans=0,
                      allow_empty_first_page=True, **kwargs):
        paginator = super(BaseListView, self).get_paginator(queryset, per_page, orphans=0,
                                                            allow_empty_first_page=True, **kwargs)
        page = self.kwargs.get(self.page_kwarg) or self.request.GET.get(self.page_kwarg) or 1
        page_number = 0
        try:
            page_number = int(page)
        except ValueError:
            if page == 'last':
                page_number = paginator.num_pages

        new_page_number = page_number

        if page_number < 1:
            new_page_number = 1
        elif page_number > paginator.num_pages:
            new_page_number = paginator.num_pages
        if new_page_number != page_number:
            self.kwargs[self.page_kwarg] = new_page_number
        return paginator

    def get_page_number(self, i):
        if i == PREVIOUS_PAGE:
            if self.page_num > 1:
                return mark_safe(u'<li><a href="%s">&laquo;</a></li> ' % (
                    escape(self.get_query_string({self.page_kwarg: self.page_num - 1}))))
            else:
                return mark_safe(u'<li class="disabled"><span >&laquo;</span></li> ')
        elif i == NEXT_PAGE:
            if self.page_num < self.paginator.num_pages:
                return mark_safe(u'<li><a href="%s">&raquo;</a></li> ' % (
                    escape(self.get_query_string({self.page_kwarg: self.page_num + 1}))))
            else:
                return mark_safe(u'<li class="disabled"><span >&raquo;</span></li> ')
        elif i == DOT:
            return mark_safe(u'<li><span class="dot-page">...</span></li>')
        elif i == self.page_num:
            return mark_safe(u'<li class="active"><span>%d</span></li> ' % i)
        else:
            return mark_safe(u'<li><a href="%s">%d</a></li> ' % (
                escape(self.get_query_string({self.page_kwarg: i})), i))

    def page_range(self, paginator, page_num, page_type='normal'):
        """
        Generates the series of links to the pages in a paginated list.
        """

        ON_EACH_SIDE = {'normal': 5, 'small': 3}.get(page_type, 3)
        ON_ENDS = 2
        self.paginator = paginator
        self.page_num = page_num
        total_pages_num = paginator.num_pages
        # If there are 10 or fewer pages, display links to every page.
        # Otherwise, do some fancy
        if total_pages_num <= 10:
            page_range = range(1, total_pages_num + 1)
        else:
            # Insert "smart" pagination links, so that there are always ON_ENDS
            # links at either end of the list of pages, and there are always
            # ON_EACH_SIDE links at either end of the "current page" link.
            page_range = []
            if page_num > (ON_EACH_SIDE + ON_ENDS):
                page_range.extend(range(1, ON_EACH_SIDE))
                page_range.append(DOT)
                page_range.extend(
                    range(page_num - ON_EACH_SIDE, page_num + 1))
            else:
                page_range.extend(range(1, page_num + 1))
            if page_num < (total_pages_num - ON_EACH_SIDE - ON_ENDS - 1):
                page_range.extend(
                    range(page_num + 1, page_num + ON_EACH_SIDE + 1))
                page_range.append(DOT)
                page_range.extend(range(
                    total_pages_num - ON_ENDS, total_pages_num + 1))
            else:
                page_range.extend(range(page_num + 1, total_pages_num + 1))

        page_range.insert(0, PREVIOUS_PAGE)
        page_range.append(NEXT_PAGE)
        return {
            'page_range': map(self.get_page_number, page_range),
        }

    def get_context_data(self, **kwargs):
        kwargs = super(BaseListView, self).get_context_data(**kwargs)

wadmin/templates/wadmin/ad_test.html
{% extends 'wadmin/base.html' %}

{% block body %}
    <iframe src="http://www.sina.com.cn" id="ifid"></iframe>
    <div onclick="alert('1');">
        <script>
            var dsaid = 27525;
            var dwidth = 960;
            var dheight = 60;
        </script>
        <script type="text/javascript" src="http://unionjs.dianxin.com/showPic.js" name="showpic"
                charset="utf-8"></script>
        <script type="text/javascript">
            var dianxin_said = 27526;
            var dianxin_width = 960;
            var dianxin_height = 60;
        </script>
        <script type="text/javascript" src="http://unionjs.dianxin.com/dianxin_showcc.js" charset="utf-8"></script>
    </div>
    <script>

        function injectClick() {
            $('iframe').each(function () {

                $(this).find("body").attr("onclick", "alert('click')");
            });

        }

        function testIf() {
            $('#ifid').find("body").attr("onclick", "alert('click')");
        }

        //setTimeout(injectClick,3000);
        testIf();
    </script>
{% endblock %}

wadmin/templates/wadmin/article.html
{% extends 'wadmin/frame.html' %}
{% block content %}
    <div class="panel">
        <div class="panel-body">
            {{ object.content|safe }}
        </div>
    </div>
    <script>
        var dsaid = 27525;
        var dwidth = 960;
        var dheight = 60;
    </script>
    <script type="text/javascript" src="http://unionjs.dianxin.com/showPic.js" name="showpic"
            charset="utf-8"></script>
    <script type="text/javascript">
        var dianxin_said = 27526;
        var dianxin_width = 960;
        var dianxin_height = 60;
    </script>
    <script type="text/javascript" src="http://unionjs.dianxin.com/dianxin_showcc.js" charset="utf-8"></script>
{% endblock %}

wadmin/templates/wadmin/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/3.3.1/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}wadmin/css/base.css">
    <script src="{{ STATIC_URL }}js/jquery-1.11.1.min.js"></script>
    <script src="{{ STATIC_URL }}wadmin/js/base.js"></script>
    <link href="{{ STATIC_URL }}jquery-ui/jquery-ui.min.css" rel="stylesheet">
    <script src="{{ STATIC_URL }}jquery-ui/jquery-ui.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="{{ STATIC_URL }}js/respond.min.js"></script>
        <script src="{{ STATIC_URL }}js/html5shiv.js"></script>
    <![endif]-->
    <style>
        @-moz-document url-prefix() {
            fieldset {
                display: table-cell;
            }
        }
    </style>
    {% block ext_header %}{% endblock %}
</head>
<body class="{% block body-class %}{% endblock %}">
{% block body %}
{% endblock %}

<script src="{{ STATIC_URL }}bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}bootstrap/3.3.1/js/bootstrap-datetimepicker.js"></script>
<script src="{{ STATIC_URL }}bootstrap/3.3.1/js/bootstrap-datetimepicker.zh-CN.js"></script>
</body>
</html>

wadmin/templates/wadmin/change_password.html
{% extends 'wadmin/frame_edit.html' %}
{% block fields %}
    {% with field=form.password_old %}
        {% include 'wadmin/inclute/form_field_password.html' %}
    {% endwith %}
    {% with field=form.password_new1 %}
        {% include 'wadmin/inclute/form_field_password.html' %}
    {% endwith %}
    {% with field=form.password_new2 %}
        {% include 'wadmin/inclute/form_field_password.html' %}
    {% endwith %}
{% endblock %}
{% block buttons %}
    <button type="submit" class="btn btn-primary">修改密码</button>
{% endblock %}

wadmin/templates/wadmin/frame.html
{% extends 'wadmin/base.html' %}
{% block title %}{{ view.title }}{% endblock %}
{% block  body %}
    <!-- Frame -->

    <!-- navbar -->
    <div id="top-nav" class="navbar navbar-xs navbar-inverse">
        <div class="navbar-header">
            <p class="navbar-brand">广告Demo</p>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right" style="margin-right: 5px">
                {% if user.is_active %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
                            <strong>欢迎， {{ user.get_username }}</strong> <span class="caret"></span></a>
                        <ul id="g-account-menu" class="dropdown-menu" role="menu">
                            <li><a href="{% url 'wadmin:change_password' %}"><span
                                    class="glyphicon glyphicon-cog"></span>
                                更改密码</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'wadmin:logout' %}"><span class="glyphicon glyphicon-log-out"></span><span
                            class="hidden-sm hidden-xs">注销</span></a>
                    </li>
                {% else %}
                    <li><a href="{% url 'wadmin:login' %}"><span class="glyphicon glyphicon-log-in"></span><span
                            class="hidden-sm hidden-xs">登录</span></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <!-- navbar end -->
    <div class=" container-fluid">
        <div class="clearfix row">
            <!-- Left menu-->
            <div id="left-side" class="col-md-2 col-lg-2 hidden-sm hidden-xs">

                {% include 'wadmin/inclute/sitemenu.html' %}


            </div>
            <!-- Left menu end-->
            <div class="col-md-9 col-lg-10">
                {% if messages %}
                    {% for message in messages %}
                        {% ifequal message.tags 'error' %}
                            <div class="alert alert-danger"
                                 role="alert">{{ message }}</div>
                        {% else %}
                            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}"
                                 role="alert">{{ message }}</div>
                        {% endifequal %}
                    {% endfor %}

                {% endif %}
                {% block content-title %}
                    <div class="navbar content-navbar navbar-default navbar-xs" data-toggle="breakpoint"
                         data-class-xs="navbar content-navbar navbar-inverse navbar-xs"
                         data-class-sm="navbar content-navbar navbar-default navbar-xs">
                        <div class="navbar-header">

                            <span class="navbar-brand">
                                {% if view.parents %}
                                    {% for parent in view.parents %}
                                        <span class="parent-brand"><a
                                                href="{{ parent.url }}"><u>{{ parent.name }}</u></a> <span
                                                class="glyphicon glyphicon-chevron-right"></span></span>
                                    {% endfor %}
                                {% endif %}
                                {{ view.title }}
                            </span>

                        </div>
                    </div>
                {% endblock %}
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
    <!-- Frame end-->
{% endblock %}

wadmin/templates/wadmin/frame_edit.html
{% extends 'wadmin/frame.html' %}
{% block content %}

    <form action="" class="form-horizontal" method="post" role="form">
        <div class="form-container row">
            <div class="col-md-12 ">
                <div class="panel panel-default fieldset">
                    <div class="panel-body">
                        {% include 'wadmin/inclute/form_non_field_errors.html' %}
                        {% block fields %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                {% block buttons %}{% endblock %}
            </div>
        </div>
    </form>
{% endblock %}

wadmin/templates/wadmin/home.html
{% extends 'wadmin/frame.html' %}
{% block ext_header %}
    <script src="{{ STATIC_URL }}wadmin/js/change_list.js"></script>
{% endblock %}
{% block content %}
    <form action="" method="post" xmlns="http://www.w3.org/1999/html">
        <nav>
            <ul class="pagination">
                {% for page in page_range %}
                    {{ page }}
                {% endfor %}
            </ul>
        </nav>


        {% for object in object_list %}
            <a href="{% url 'wadmin:article' object.id %}">
                <div class="well">
                    作者:{{ object.user.username }}<br>
                    {{ object.title }}

                    <div class="text-right">{{ object.create_time }}</div>
                    <div class="text-right">访问次数:{{ object.visit_count }}</div>
                </div>
            </a>
        {% endfor %}

        {% include 'wadmin/inclute/change_list_delete_confirm.html' %}
    </form>
    <nav>
        <ul class="pagination">
            {% for page in page_range %}
                {{ page }}
            {% endfor %}
        </ul>
    </nav>
{% endblock %}

wadmin/templates/wadmin/login.html
{% extends 'wadmin/base.html' %}
{% block ext_header %}
    <style>
        #login_panel {
            box-shadow: 0 0 1em 1em #ccc;
            max-width: 350px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 50px
        }

        #img_code_view {
            cursor: pointer;
        }
    </style>
    <script>
        function change_img_code() {
            var img = $('#img_code_view');
            var rand = Math.random();
            img.attr('src', "{% url 'wadmin:img_code' %}?t=" + rand);
        }
    </script>
{% endblock %}
{% block body %}

    <div class="container">

        <form action="" method="post" class="form">
            <div class="panel panel-default panel-single" id="login_panel">

                <div class="panel-heading">

                    <h2>Demo登录</h2>
                </div>
                <div class="panel-body">
                    {% if form.non_field_errors %}
                        <div class="alert alert-block alert-danger">
                            <ul>
                                {{ form.non_field_errors|unordered_list }}
                            </ul>
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <div class="input-group input-group-lg {% if form.username.errors %}has-error{% endif %}">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>

                            <input id="username" type="text" class="form-control  " name="username" placeholder="用户名"
                                   type="text">
                        </div>
                        {% for error in form.username.errors %}
                            <p id="error_{{ forloop.counter }}_{{ field.auto_id }}"
                               class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>

                    <div class="form-group">
                        <div class="input-group input-group-lg {% if form.password.errors %}has-error{% endif %}">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>

                            <input id="password" type="password" class="form-control" name="password" placeholder="密码"
                                   type="text">
                        </div>
                        {% for error in form.password.errors %}
                            <p id="error_{{ forloop.counter }}_{{ field.auto_id }}"
                               class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>

                    <div class="form-group">
                        <div class="input-group input-group-lg {% if form.img_code.errors %}has-error{% endif %}">
                            <div class="input-group-addon "><img id="img_code_view" onclick="change_img_code();"
                                                                 width="90" height="20"
                                                                 src="{% url 'wadmin:img_code' %}"></div>
                            <input id="img_code" type="text" class="form-control" name="img_code" placeholder="验证码"
                                   type="text">


                        </div>
                        {% for error in form.img_code.errors %}
                            <p id="error_{{ forloop.counter }}_{{ field.auto_id }}"
                               class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <input class="btn btn-primary btn-block" type="submit" value="提交">

                </div>

                <div class="panel-footer">

                    <div><a href="{% url 'wadmin:register' %}?next={{ url }}">注册</a></div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}